name: Update Image Every Hour

on:
  schedule:
    - cron: '*/10 * * * *'


  workflow_dispatch:  # Allows manual triggering

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repository

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use latest Python 3 version

      - name: Install Dependencies
        run: pip install -r requirements.txt  # If needed

      - name: Run Python Script
        run: python get_cotd.py  # Replace with your script filename

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update image" || exit 0  # Prevent failure if no changes
          git push
